/*
 * GUI.java
 *
 * Created on Nov 15, 2011, 12:46:05 PM
 */
package pj.d10roller.view;

import java.awt.Toolkit;
import pj.d10roller.controller.Controller;

/**
 *
 * @author Paul Jones
 */
public class GUI extends javax.swing.JFrame {

  /** Creates new form GUI */
  public GUI() {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        critOptionGroup = new javax.swing.ButtonGroup();
        rollButton = new javax.swing.JButton();
        resultsScrollPane = new javax.swing.JScrollPane();
        resultsTextArea = new javax.swing.JTextArea();
        tabPanel = new javax.swing.JTabbedPane();
        keepsRollPanel = new javax.swing.JPanel();
        rollsLabel = new javax.swing.JLabel();
        rollsSpinner = new javax.swing.JSpinner();
        keepsLabel = new javax.swing.JLabel();
        keepsSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        crit8Button = new javax.swing.JRadioButton();
        crit9Button = new javax.swing.JRadioButton();
        crit10Button = new javax.swing.JRadioButton();
        percentileRollPanel = new javax.swing.JPanel();
        percentileLabel = new javax.swing.JLabel();
        percentileSpinner = new javax.swing.JSpinner();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("d10roller");
        setIconImage(Toolkit.getDefaultToolkit().getImage("pj/d10roller/view/icon.png"));
        setResizable(false);

        rollButton.setFont(new java.awt.Font("Cantarell", 0, 18));
        rollButton.setText("MUNDO ROLL!");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPressed(evt);
            }
        });

        resultsTextArea.setColumns(20);
        resultsTextArea.setEditable(false);
        resultsTextArea.setRows(5);
        resultsScrollPane.setViewportView(resultsTextArea);

        tabPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        keepsRollPanel.setBorder(null);

        rollsLabel.setFont(new java.awt.Font("Cantarell", 0, 18));
        rollsLabel.setText("Rolls");

        rollsSpinner.setFont(new java.awt.Font("Cantarell", 0, 18));
        rollsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        keepsLabel.setFont(new java.awt.Font("Cantarell", 0, 18));
        keepsLabel.setText("Keeps");

        keepsSpinner.setFont(new java.awt.Font("Cantarell", 0, 18));
        keepsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18));
        jLabel1.setText("Explode On:");

        critOptionGroup.add(crit8Button);
        crit8Button.setText("8");

        critOptionGroup.add(crit9Button);
        crit9Button.setText("9");

        critOptionGroup.add(crit10Button);
        crit10Button.setSelected(true);
        crit10Button.setText("10");

        javax.swing.GroupLayout keepsRollPanelLayout = new javax.swing.GroupLayout(keepsRollPanel);
        keepsRollPanel.setLayout(keepsRollPanelLayout);
        keepsRollPanelLayout.setHorizontalGroup(
            keepsRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keepsRollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keepsRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keepsRollPanelLayout.createSequentialGroup()
                        .addComponent(rollsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rollsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(keepsRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keepsRollPanelLayout.createSequentialGroup()
                        .addComponent(crit8Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crit9Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crit10Button)
                        .addGap(100, 100, 100))
                    .addGroup(keepsRollPanelLayout.createSequentialGroup()
                        .addComponent(keepsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keepsSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        keepsRollPanelLayout.setVerticalGroup(
            keepsRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keepsRollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keepsRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollsLabel)
                    .addComponent(rollsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keepsLabel)
                    .addComponent(keepsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keepsRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(crit8Button)
                    .addComponent(crit9Button)
                    .addComponent(crit10Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.addTab("Keeps Roll", keepsRollPanel);

        percentileLabel.setFont(new java.awt.Font("Cantarell", 0, 18));
        percentileLabel.setText("Modifier");

        percentileSpinner.setFont(new java.awt.Font("Cantarell", 0, 18));
        percentileSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout percentileRollPanelLayout = new javax.swing.GroupLayout(percentileRollPanel);
        percentileRollPanel.setLayout(percentileRollPanelLayout);
        percentileRollPanelLayout.setHorizontalGroup(
            percentileRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, percentileRollPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(percentileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentileSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );
        percentileRollPanelLayout.setVerticalGroup(
            percentileRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(percentileRollPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(percentileRollPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentileLabel)
                    .addComponent(percentileSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tabPanel.addTab("Percentile", percentileRollPanel);

        clearButton.setFont(new java.awt.Font("Cantarell", 0, 18));
        clearButton.setText("MUNDO SELL!");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonbuttonPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(rollButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addGap(36, 36, 36))
                    .addComponent(resultsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void buttonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPressed
    switch(tabPanel.getSelectedIndex()) {
      case 0:
        int crit;
        if(crit10Button.isSelected())
          crit = 10;
        else if(crit9Button.isSelected())
          crit = 9;
        else
          crit = 8;
        updateDisplay(Controller.calcKeepRoll((Integer)rollsSpinner.getValue(),
                (Integer)keepsSpinner.getValue(), crit));
        break;
      case 1:
        updateDisplay(Controller.calcPercentileRoll(
                (Integer)percentileSpinner.getValue()));
        break;
    }
  }//GEN-LAST:event_buttonPressed

  private void clearButtonbuttonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonbuttonPressed
    clearDisplay();
  }//GEN-LAST:event_clearButtonbuttonPressed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {

      @Override
      public void run() {
        new GUI().setVisible(true);
      }
    });
  }
  
  /**
   * Adds an additional line of text to the top of the text area
   * @param newStr The line to be added to the display
   */
  public void updateDisplay(String newStr) {
    resultsTextArea.setText(newStr + "\n" + resultsTextArea.getText());
    resultsTextArea.setCaretPosition(0);
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton crit10Button;
    private javax.swing.JRadioButton crit8Button;
    private javax.swing.JRadioButton crit9Button;
    private javax.swing.ButtonGroup critOptionGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel keepsLabel;
    private javax.swing.JPanel keepsRollPanel;
    private javax.swing.JSpinner keepsSpinner;
    private javax.swing.JLabel percentileLabel;
    private javax.swing.JPanel percentileRollPanel;
    private javax.swing.JSpinner percentileSpinner;
    private javax.swing.JScrollPane resultsScrollPane;
    private javax.swing.JTextArea resultsTextArea;
    private javax.swing.JButton rollButton;
    private javax.swing.JLabel rollsLabel;
    private javax.swing.JSpinner rollsSpinner;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables

  private void clearDisplay() {
    resultsTextArea.setText("");
  }
}
